AWSTemplateFormatVersion: 2010-09-09
Transform:
- AWS::Serverless-2016-10-31
- AWS::CodeStar

Parameters:
  ProjectId:
    Type: String
    Description: AWS CodeStar projectID used to associate new resources to team members
  CodeDeployRole:
    Type: String
    Description: IAM role to allow AWS CodeDeploy to manage deployment of AWS Lambda functions
  Stage:
    Type: String
    AllowedValues:
      - dev
      - prod
    Description: The name for a project pipeline stage, such as Staging or Prod, for which resources are provisioned and deployed.
    Default: 'dev'


Resources:
# lambda
  GrowthchartLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/controller/index.handler
      Runtime: nodejs12.x
      Timeout: 300
      MemorySize: 256
      Environment:
        Variables:
          NODE_ENV: production
          plantsTable: !Sub '${ProjectId}-plants-table'
      Policies:
        Statement:
        - Effect: Allow
          Action:
            - dynamodb:GetItem
            - dynamodb:UpdateItem
            - dynamodb:PutItem
            - dynamodb:BatchGetItem
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:BatchWriteItem
          Resource: !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${ProjectId}-plants-table"

      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /growthchart/plant
            Method: get
        PostEvent:
          Type: Api
          Properties:
            Path: /growthchart/plant
            Method: post
  # Tables
  PlantTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'awscodestar-${ProjectId}-plantstable-Growthchart'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: plantId
          AttributeType: S
      KeySchema:
        - AttributeName: plantId
          KeyType: HASH
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      StreamSpecification:
        StreamViewType: NEW_IMAGE
      SSESpecification:
        SSEEnabled: true
  PlantDataTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: plantId
        Type: String
      TableName: !Sub "${ProjectId}-plants-table"